---
Name: arillo-elements
After:
  - 'silverstripe/versioned'
---
BetterButtonsActions:
  edit:
    BetterButtonFrontendLinksAction: false
  versioned_edit:
    BetterButton_Rollback: true
    BetterButton_Unpublish: true
    Group_Versioning: false
    BetterButtonFrontendLinksAction: false

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - arillo/silverstripe-elements:client/css/cms.css

Arillo\Elements\ElementBase:
  extensions:
    - Arillo\Elements\ElementsExtension

Page:
  extensions:
    - Arillo\Elements\ElementsExtension
