---
Name: elements
---

BetterButtonsActions:
  edit:
    BetterButtonFrontendLinksAction: false
  versioned_edit:
    BetterButton_Rollback: true
    BetterButton_Unpublish: true
    Group_Versioning: false
    BetterButtonFrontendLinksAction: false

ElementBase:
  extensions:
    - FluentExtension
    - FluentFilteredExtension
