---
Name: arillo-elements
After:
  - 'silverstripe/versioned'
  - '#versionedgridfield'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - arillo/silverstripe-elements:client/css/cms.css

Arillo\Elements\ElementBase:
  extensions:
    - Arillo\Elements\ElementsExtension

Page:
  extensions:
    - Arillo\Elements\ElementsExtension

SilverStripe\Versioned\VersionedGridFieldItemRequest:
  extensions:
    - Arillo\Elements\VersionedGridFieldItemRequestExtension
